
name: aIBM Cloud Foundry - aV2Ray

env:
  1IBM_CF_API: https://api.us-south.cf.cloud.ibm.com
  1IBM_CF_APP_MEM: 256M

on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: 10 17 * * 3

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      1IBM_CF_USERNAME: ${{ secrets.1IBM_CF_USERNAME }}
      1IBM_CF_PASSWORD: ${{ secrets.1IBM_CF_PASSWORD }}
      1IBM_CF_ORG_NAME: ${{ secrets.1IBM_CF_ORG_NAME }}
      1IBM_CF_SPACE_NAME: ${{ secrets.1IBM_CF_SPACE_NAME }}
      1IBM_CF_APP_NAME: ${{ secrets.1IBM_CF_APP_NAME }}
      AV2_UUID: ${{ secrets.AV2_UUID }}
      AV2_WS_PATHS_SVMESS: ${{ secrets.AV2_WS_PATHS_SVMESS }}
      AV2_WSA_PATHS_AVLESS: ${{ secrets.AV2_WSA_PATHS_AVLESS }}

    steps:

    - name: Install Cloud Foundry CLI
      run: |
        curl -fsSL "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v7&source=github" | tar -zxC /tmp
        sudo install -m 755 /tmp/cf7 /usr/local/bin/cf
        cf version
        
    - name: Login to IBM Cloud Foundry
      run: |
        cf login \
          -a "${1IBM_CF_API}" \
          -u "${1IBM_CF_USERNAME}" \
          -p "${1IBM_CF_PASSWORD}" \
          -o "${1IBM_CF_ORG_NAME:-$1IBM_CF_USERNAME}" \
          -s "${1IBM_CF_SPACE_NAME:-dev}"
          
    - name: Download Latest Xray
      run: |
        DOWNLOAD_URL="https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip"
        curl -fsSL "$DOWNLOAD_URL" -o "latest-xray.zip"
        unzip latest-xray.zip xray geoip.dat geosite.dat
        rm latest-xray.zip
        chmod -v 755 xr*
        ./xray -version
        mv xray ${IBM_CF_APP_NAME}
        
    - name: Generate Xray Config File (VMess)
      if: ${{ env.AV2_WS_PATHS_SVMESS }}
      run: |
        base64 << 1236 > config
        {
          "log": {
            "access": "none",
            "loglevel": "error"
          },
          "inbounds": [
            {
              "port": 8082,
              "protocol": "vmess",
              "settings": {
                "clients": [
                  {
                    "id": "${AV2_UUID}",
                    "alterId": 2
                  }
                ]
              },
              "streamSettings": {
                "network":"ws",
                "wsSettings": {
                  "path": "${AV2_WS_PATHS_SVMESS}"
                }
              }
            }
          ],
          "outbounds": [
            {
              "protocol": "freedom"
            }
          ]
        }
        
    - name: Generate Xray Config File (VLESS)
      if: ${{ env.AV2_WSA_PATHS_AVLESS }}
      run: |
        base64 << 1236 > config
        {
          "log": {
            "access": "none",
            "loglevel": "error"
          },
          "inbounds": [
            {
              "port": 8082,
              "protocol": "vless",
              "settings": {
                "decryption": "none",
                "clients": [
                  {
                    "id": "${V2_UUID}"
                  }
                ]
              },
              "streamSettings": {
                "network":"ws",
                "wsSettings": {
                  "path": "${AV2_WSA_PATHS_AVLESS}"
                }
              }
            }
          ],
          "outbounds": [
            {
              "protocol": "freedom"
            }
          ]
        }
        
    - name: Generate Manifest File
      run: |
        cat << 1236 > manifest.yml
        applications:
        - name: ${1IBM_CF_APP_NAME}
          memory: ${1IBM_CF_APP_MEM}
          random-route: true
          command: base64 -d config > config.json; ./${1IBM_CF_APP_NAME} -config=config.json
          buildpacks:
          - binary_buildpack
        
    - name: Deploy Cloud Foundry App
      run: cf push
